title: "Eduard's Blog"
description: "Pilze, Natur, Wissenschaft"
author: "@hanopt"
# Use GitHub Pages–supported theme
theme: minima
#theme: jekyll-theme-slate

# Nice-to-haves (all supported by GitHub Pages)
plugins:
  - jekyll-feed
  - jekyll-sitemap
  

# Add this if using minima theme
include:
  - _includes/custom-head.html

# If you later use a custom domain, set url to https://yourdomain.com
url: "https://hanopt.github.io"
# leave baseurl empty for user sites
baseurl: ""


